name: Deploy En on Comment with Hashtag

on:
  issue_comment:
    types: [created, edited]

run-name: "海外版(${{ github.event.comment.created_at }})"

concurrency:
  group: document-prod
  cancel-in-progress: false

jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: start
        env:
            TZ: 'Asia/Tokyo'
        run: echo "GitHub Actions Start($(date '+%Y-%m-%d %H:%M:%S'))"
      - name: IP Address
        with:
          inlineScript: |
              IP=$(curl -s https://checkip.amazonaws.com/)
              echo "IP Address: $IP"
      - name: wait
        run: sleep 30
      - name: end
        env:
            TZ: 'Asia/Tokyo'
        run: echo "GitHub Actions End($(date '+%Y-%m-%d %H:%M:%S'))"

